name: fancy_on_boarding
description: A Flutter package for a quick, handy and beautiful OnBoarding screen library.
version: 1.7.0
homepage: https://github.com/xsahil03x/fancy_on_boarding

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.21.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
